/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SCC-COLLEGE
 */
public class regisform extends javax.swing.JFrame {

    /**
     * Creates new form regisform
     */
    public regisform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        p2 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        regisform = new javax.swing.JLabel();
        tb1 = new javax.swing.JTextField();
        uname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        tb2 = new javax.swing.JTextField();
        tb3 = new javax.swing.JTextField();
        pnum = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        pass = new javax.swing.JLabel();
        compass = new javax.swing.JLabel();
        regnow = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel5.setText("USERNAME");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(153, 255, 0));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel13.setText("USERNAME");

        jPasswordField3.setEditable(false);
        jPasswordField3.setBackground(new java.awt.Color(153, 255, 0));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel11.setText("PASSWORD");

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel3.setText("GRANT!");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel4.setText("GRANT!");

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel10.setText("GRANT!");

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel14.setText("GRANT!");

        jLabel25.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel25.setText("USERNAME");

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(153, 255, 0));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(153, 255, 0));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 255, 0));

        jPasswordField4.setEditable(false);
        jPasswordField4.setBackground(new java.awt.Color(153, 255, 0));

        jPasswordField2.setEditable(false);
        jPasswordField2.setBackground(new java.awt.Color(153, 255, 0));

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel9.setText("PASSWORD");

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel15.setText("PASSWORD");

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel6.setText("REGISTRATION FORM");

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel7.setText("REGISTRATION FORM");

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel12.setText("REGISTRATION FORM");

        jLabel16.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel16.setText("REGISTRATION FORM");

        jLabel18.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel18.setText("REGISTRATION FORM");

        jLabel19.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel19.setText("REGISTRATION FORM");

        jLabel22.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel22.setText("REGISTRATION FORM");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 255, 0));
        jPanel3.setForeground(new java.awt.Color(153, 255, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setForeground(new java.awt.Color(153, 255, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2.setEditable(false);
        p2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 210, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regisform.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        regisform.setText("REGISTRATION FORM");
        jPanel2.add(regisform, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 280, 60));

        tb1.setEditable(false);
        tb1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(tb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 210, 30));

        uname.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        uname.setText("USERNAME");
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 90, 50));

        email.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        email.setText("EMAIL");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, 50));

        tb2.setEditable(false);
        tb2.setBackground(new java.awt.Color(255, 255, 204));
        tb2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(tb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 210, 30));

        tb3.setEditable(false);
        tb3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(tb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 210, 30));

        pnum.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        pnum.setText("PHONE NUMBER");
        jPanel2.add(pnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 160, 50));

        p1.setEditable(false);
        p1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 210, 30));

        pass.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        pass.setText("PASSWORD");
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 90, 50));

        compass.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        compass.setText("COMFIRM PASSWORD");
        jPanel2.add(compass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 180, 50));

        regnow.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        regnow.setText("REGISTER NOW");
        regnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnowActionPerformed(evt);
            }
        });
        jPanel2.add(regnow, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 130, 30));

        cancel.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 370, 540));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 590));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void regnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regisform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regisform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regisform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regisform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regisform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel compass;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel pnum;
    private javax.swing.JLabel regisform;
    private javax.swing.JButton regnow;
    private javax.swing.JTextField tb1;
    private javax.swing.JTextField tb2;
    private javax.swing.JTextField tb3;
    private javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables
}
